# ---- Plugins ---- #
# tmux-plugins/tpm - Tmux Plugin Manager
set -g @plugin "tmux-plugins/tpm"

# tmux-plugins/tmux-continuum
set -g @plugin "tmux-plugins/tmux-continuum"

set -g @continuum-boot "on"
set -g @continuum-restore "on"

# tmux-plugins/tmux-pain-control
set -g @plugin "tmux-plugin/tmux-pain-control"

set -g @pain_resize "5"

# tmux-plugins/tmux-resurrect
set -g @plugin "tmux-plugins/tmux-resurrect"

# tmux-plugins/tmux-sensible
set -g @plugin "tmux-plugins/tmux-sensible"

# tmux-plugins/tmux-sessionist
set -g @plugin "tmux-plugins/tmux-sessionist"

# dracula/tmux - Dracula theme for tmux
set -g @plugin "dracula/tmux"

set -g @dracula-plugins "git cpu-usage gpu-usage ram-usage network-bandwidth time"
set -g @dracula-show-empty-plugins false
set -g @dracula-refresh-rate 10

set -g @dracula-show-flags false

set -g @dracula-show-powerline true
set -g @dracula-show-left-sep 
set -g @dracula-show-right-sep 

set -g @dracula-show-left-icon "yuzu-ice.tmux | #S"

set -g @dracula-cpu-display-load false
set -g @dracula-cpu-usage-label ""
set -g @dracula-cpu-usage-colors "pink dark_gray"

set -g @dracula-gpu-usage-label "󰢮 "
set -g @dracula-gpu-usage-colors "green dark_gray"

set -g @dracula-ram-usage-label "󰘚"
set -g @dracula-ram-usage-colors "cyan dark_gray"

set -g @dracula-network-bandwidth-colors "orange dark_gray"

set -g @dracula-time-format "%F %R %a"
set -g @dracula-time-colors "dark_purple white"

# ---- Settings ----
# Set leader key as Ctrl+x, instead of Ctrl+b
set -g prefix C-x

# Set vi mode for copy mode
setw -g mode-keys vi

# Make index starts from 1
set -g base-index 1
setw -g pane-base-index 1

# Set status position to top
set-option -g status-position top

# ---- Keybinds ----
# Reload tmux config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Session switcher list order by its name
bind s choose-tree -sZ -O name

# Enter copy-mode like a visual mode in vim
bind v copy-mode

# vim-like bindings for copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# ---- TPM initialization ----
# keep this line at the very bottom of tmux.conf
run '~/.config/tmux/plugins/tpm/tpm'
