#---------#
# Plugins #
#---------#
# TPM - Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Dracula theme for tmux
set -g @plugin 'dracula/tmux'

set -g @dracula-plugins 'git cpu-usage gpu-usage ram-usage network-bandwidth time'
set -g @dracula-show-empty-plugins false
set -g @dracula-refresh-rate 10

set -g @dracula-show-flags false

set -g @dracula-show-powerline true
set -g @dracula-show-left-sep 
set -g @dracula-show-right-sep 

set -g @dracula-show-left-icon 'yuzu-ice.tmux | #S'

set -g @dracula-cpu-display-load false
set -g @dracula-cpu-usage-label ""
set -g @dracula-cpu-usage-colors "pink dark_gray"

set -g @dracula-gpu-usage-label "󰢮 "
set -g @dracula-gpu-usage-colors "green dark_gray"

set -g @dracula-ram-usage-label "󰘚"
set -g @dracula-ram-usage-colors "cyan dark_gray"

set -g @dracula-network-bandwidth-colors "orange dark_gray"

set -g @dracula-time-format "%F %R %a"
set -g @dracula-time-colors "dark_purple white"

#----------#
# Keybinds #
#----------#
# Reload tmux config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# vim motion-like pane navigating
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim motion-like pane resizing
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Navigating between windows using leader+[ and leader+], previous and next respectively
unbind p
unbind [
bind [ previous-window

unbind n
unbind ]
bind ] next-window

# Window swapping
unbind '{'
bind '{' swap-window -t -1\; select-window -t -1

unbind '}'
bind '}' swap-window -t +1\; select-window -t +1

# Better pane splitting
unbind %
bind | split-window -h

unbind \"
bind - split-window -v

# Pane swapping
bind C-h swap-pane -U
bind C-l swap-pane -D

# Enter copy-mode like a visual mode in vim
bind v copy-mode

# Session switcher list order by its name
bind s choose-tree -sZ -O name

# vim-like bindings for copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

#----------#
# Settings #
#----------#
# Set leader key as Ctrl+x, instead of Ctrl+b
set -g prefix C-x

# Set vi mode for copy mode
setw -g mode-keys vi

# Make index starts from 1
set -g base-index 1
setw -g pane-base-index 1

# Set status position to top
set-option -g status-position top

# Automatic session restoration
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
